dist: trusty
language: python
python:
  - "3.6"

sudo: required

cache:
  directories:
  - ${TRAVIS_BUILD_DIR}/pycoreir
  - ${TRAVIS_BUILD_DIR}/pysmt
  - ${TRAVIS_BUILD_DIR}/coreir
  - /home/travis/.smt_solvers/python-bindings-3.6

addons:
  apt:
    update: true
    sources:
    - ubuntu-toolchain-r-test
    packages:
     - g++-4.9
     - wget
     - unzip
     - build-essential
     - python3
     - automake
     - libgmp-dev
     - curl
     - nano
     - python3-dev
     - libboost-dev
     - default-jdk
     - libclang-dev
     - llvm
     - llvm-dev
     - lbzip2
     - libncurses5-dev
     - python3-nose
     - iverilog

install:
  - pip install six pyparsing coreir pyverilog
  - bash scripts/travis_install.sh

env:
 - PYTHONPATH="${TRAVIS_BUILD_DIR}/pycoreir":"${TRAVIS_BUILD_DIR}/pysmt":"${TRAVIS_BUILD_DIR}/pysmt/bindings:${PYTHONPATH}" LD_LIBRARY_PATH="${TRAVIS_BUILD_DIR}/pycoreir/lib":"${TRAVIS_BUILD_DIR}/pysmt/bindings":${LD_LIBRARY_PATH}"


script: nosetests tests -v